# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.51.1"

  on_macos do
    on_intel do
      sha256 "3900351bace1706c65e832721a665fa8b54e1fafd49140eb0df3dec339dc9bb0"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "c25ade9ca87a454b90a30d83e7be8162390ef1e505c03ff8c4f234f9c11050ec"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3ac83ebace9886f826f82b19d6cafc96c8fd2eb555a5fb1e177209f0d188789"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "b2f4f1f297e0efe00e7c705862ec2e6a60640e85197d637b28a5f066b6cd0a85"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
