# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.53.1"

  on_macos do
    on_intel do
      sha256 "8d98491337c25a7a2102561abe94f3b2d135e01036ba8e871ce66bedcde1eac8"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "8a1b7a5741ac0c3f063b1d99e5edbb82d2654920ce0de0941083b4b5e87023ed"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "212e9fd848046615048e45e60431505e66041c0e8f6bc795b250239f9d30951a"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "31cc1272cadb116436d0eb53a47d8df911f40f8f8dd8a767b9e6b461505ec793"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
