# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxhunt.dev/"
  version "4.41.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-dump.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  on_macos do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "7c4a49c778d356a7b67eb96187c0c1e02bccb3c756e1a72e18c4f16ecefe07f0"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "bb18bbacea76554ad39e7a7ac49ba90ddcf014d775688d90d60241dee8ae4898"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "682dd9dfbf532555643d29e80e79292f244e2bf519007ce897967632999bba06"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "20752257a595d863f607a004f1d1565e75eda6a0249f6e8f3155e3d94de5a1da"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required
end
